// Planets
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
export const DELETE_PLANET_SUCCESS = 'DELETE_PLANET_SUCCESS';
export const PLANET_PROFILE_SUCCESS = 'PLANET_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
