// Planets
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
export const DELETE_PLANET_SUCCESS = 'DELETE_PLANET_SUCCESS';
export const PLANET_PROFILE_SUCCESS = 'PLANET_PROFILE_SUCCESS';

// Planets
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const TRACK_PROFILE_SUCCESS = 'TRACK_PROFILE_SUCCESS';
// Planets
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS';
export const ARTIST_PROFILE_SUCCESS = 'ARTIST_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
